### ISSUE TITLE
Update link to red-data-tools

### ISSUE THREAD

**Issue by heronshoes** [red-data-tools/red_amber#210]
This project is successfully migrated to red-data-tools! :tada:

(It's serious, not an April Fool's work).

So old link to `heronshoes/red_amber/*` in everywhere should be changed as `red-data-tools/red_amber/*` even it is redirected to.

**Comment by Soumya-Kushwaha** [comment]
Hey, can you let me know which files should this change be made in?

**Comment by heronshoes** [comment]
Hi @Soumya-Kushwaha ,

I think `grep -nr *.md *.gemspec -e heronshoes/red_amber` will show you the place to chage.

**Comment by heronshoes** [comment]
Thank you for the prompt work!
I will merge this.
