### ISSUE TITLE
Raises error in Ractor

### ISSUE THREAD

**Issue by KitaitiMakoto** [red-data-tools/red_amber#289]
Hi,

I found `DataFrame#each_row` raises an error in Ractor block:

```ruby
df = DataFrame.new(numbers: [1, 2, 3, 4])
Ractor.make_shareable(df)
ractor = Ractor.new {
  d = Ractor.receive
  d.each_row.to_a
}
ractor.send df
ractor.take
# => vendor/bundle/ruby/3.3.0/gems/red-arrow-14.0.2/lib/arrow/chunked-array.rb:50:in `chunks': can't modify frozen Arrow::ChunkedArray: #<Arrow::ChunkedArray:0x12103b1b0ptr=0x6000025d9be0 [ (FrozenError)
#   [
#     1,
#     2,
#     3,
#     4
#   ]
# ]>
```

though I'm not sure RedAmber is intended to be used in Ractor block or not...

A workaround is to access `ChunkedArray` before you pass data frame to Ractor to instantiate `ChunkedArray`'s instance variable:

```ruby
df.vectors.each { |v| v.data[0] }
```

**Comment by kou** [comment]
Ah, it should be fixed in red-arrow.
Could you open a new issue to https://github.com/apache/arrow ?

**Comment by KitaitiMakoto** [comment]
@kou 
Okay, done: https://github.com/apache/arrow/issues/39488
